# Generated by Django 5.0.9 on 2026-08-11 04:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSAProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 format, e.g. +919876543210.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text="Rate in the platform's base currency.", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average parent rating from 0.00 to 5.00.', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Background check and credentials confirmed.')),
                ('accepting_bookings', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LSA profile',
                'verbose_name_plural': 'LSA profiles',
                'db_table': 'lsa_profile',
                'ordering': ['-rating', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 format, e.g. +919876543210.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('child_name', models.CharField(blank=True, max_length=150)),
                ('child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'parent',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_reference', models.CharField(db_index=True, help_text='Identifier returned by the payment gateway.', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=16)),
                ('method', models.CharField(blank=True, max_length=40)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_id', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'skill',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Human-friendly identifier shared with the parent, e.g. HB-7F3A9C2D.', max_length=24, unique=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('session_mode', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person')], default='ONLINE', max_length=16)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING_PAYMENT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('lsa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.lsaprofile')),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.CheckConstraint(check=models.Q(('child_age__isnull', True), ('child_age__lte', 25), _connector='OR'), name='parent_child_age_within_range'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.parent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='lsaprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='lsas', to='bookings.skill'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['lsa', 'status', 'scheduled_start', 'scheduled_end'], name='booking_overlap_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['parent', '-scheduled_start'], name='booking_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_start'], name='booking_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', Decimal('0.00'))), name='booking_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED'))), fields=('lsa', 'scheduled_start', 'scheduled_end'), name='uniq_active_booking_per_lsa_slot'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', Decimal('0.00'))), name='payment_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='lsaprofile',
            index=models.Index(fields=['is_active', 'is_verified', 'accepting_bookings'], name='lsa_availability_idx'),
        ),
        migrations.AddIndex(
            model_name='lsaprofile',
            index=models.Index(fields=['-rating', 'hourly_rate'], name='lsa_rating_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='lsaprofile',
            index=models.Index(fields=['city', 'years_of_experience'], name='lsa_city_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='lsaprofile',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', Decimal('0.00')), ('rating__lte', Decimal('5.00'))), name='lsa_rating_between_zero_and_five'),
        ),
        migrations.AddConstraint(
            model_name='lsaprofile',
            constraint=models.CheckConstraint(check=models.Q(('hourly_rate__gte', Decimal('0.00'))), name='lsa_hourly_rate_non_negative'),
        ),
    ]
